### ISSUE TITLE
Key considerations is missing from top navigation

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Websites#123]
This is inconsistent with the other 'top level' items that appear in the left hand sidebar. Should it be in the top level navigation?

**Comment by caprenter** [comment]
This is an inconsistency. Should it be in the top in navigation? Maybe.

The fact that it is not in the top navigation is not necessarily a problem. ["Key Considerations" as a top level navigation item could be problematic as top level items are not clearly delimited]

Either way I don't think this is of such importance that it needs addressing before March. I'm going to move it to a Future milestone

**Comment by stevieflow** [comment]
Im thinking a reconfiguration of the Guidance folder might be the way to solve this.

The guidance folder could contain sub folders:

- key considerations
- how to publish
- organisation identifiers
- licencing

I'd also advocate that the org/activity overview sections are moved from Reference to Guidance, but appreciate that this discussion is getting out of scope of the original Issue

**Comment by caprenter** [comment]
So what is the way froward here - do we need to discuss?

**Comment by stevieflow** [comment]
Slight rethink on Key Considerations

Have attempted to move this into the Introduction folder via https://github.com/IATI/IATI-Websites/issues/123#ref-pullrequest-56541208

Closing this particular ticket, therefore
