### ISSUE TITLE
Heading padding on individual element reference pages

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Websites#127]
On, e.g. http://dev.iatistandard.org/201/activity-standard/iati-activities/iati-activity/transaction/sector/narrative/

the padding between
Changelog
and 
Developer Tools
 is inconcistent

This is not across every page however, so may not be a simple fix

**Comment by amy-silcock** [comment]
No progress since 2015

**Comment by andylolz** [comment]
Adding something like:

```css
.section {
    margin-bottom: 20px;
}
```

…to [style.css](https://github.com/IATI/IATI-Websites/blob/master/iatistandard/_static/style.css) would probably do the trick here.

**Comment by samuele-mattiuzzo** [comment]
Hi @andylolz thanks for your contribution, but it's not relevant anymore.

**Comment by andylolz** [comment]
> but it's not relevant anymore.

This was closed due to lack of progress – not because it’s irrelevant. The issue still appears to be present:
http://reference.iatistandard.org/203/activity-standard/iati-activities/iati-activity/transaction/sector/narrative/

**Comment by andylolz** [comment]
Ahh, I see – It’s not relevant because the reference site theme is due to be decommissioned. Okay gotcha, no problem.
