### ISSUE TITLE
mark required attributes as required on the website

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Websites#129]
I guess this is single source of truth to website conversion work, but currently attributes that are require by the schema are not marked as such on the website.

Assigning to @Bjwebb, but I may take a look if there is time.

N.B. This probably could also be done to the 1.05 and 1.04 sites

**Comment by Bjwebb** [comment]
I don't think I'm going to get round to looking into this before March, so I've unassigned myself.

**Comment by caprenter** [comment]
Realistically, this is way down the list of priorities, so moved to a Future milestone

**Comment by samuele-mattiuzzo** [comment]
only an issue in v1, which will be deprecated soon. also very low priority, so no action
