### ISSUE TITLE
Moving overview sections 

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Websites#130]
Proposal on how we reposition / arrange sections
# Reference section - element definition sections

Current problem - the element definition pages are too nested within their current directory
## Proposal

**make each root element the first page for each section**

The reference section - http://iatistandard.org/reference/ -should have the element definition pages in their own directory, rather than nested in the current sections.

The first page of each element defintion section would be:
- org - http://iatistandard.org/organisation-standard/iati-organisations/
- activity - http://iatistandard.org/activity-standard/iati-activities/

NB: this would miss a section "homepage" - but this could be all explained better up at http://iatistandard.org/reference/
# Overview pages

Current issue: the overview pages could be seen as Guidance materials
## Proposal(s)

**rename and move Overview pages**

1- rename Overview to Useage Guidance, or similar
2 - rehouse the overview sections in the Guidance section: http://iatistandard.org/guidance/
# Organisation IDs document

Current issue: this doesn't "sit" well in the reference section - it is more about Guidance
## Proposal

**Move Org ID to Guidance section**

Moving the Org ID section to Guidance would be useful - this may or may not sit with the above mentioned Usage Guidance materials / folder
# Actions

to be discussed / refined at team mtg - 1/2nd Oct

@bill-anderson

**Comment by amy-silcock** [comment]
The positioning of the overview pages won't be moved until they are transitioned into https://iatistandard.org/en/. This will happen later on in the website project.
