### ISSUE TITLE
URLs of archived schemas

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Websites#140]
There seems to be an inconsistency with the URL of 2.01 and 1.04 (issue raised @el-clemente):

eg:

2.01 - http://dev.iatistandard.org/201/schema/downloads/iati-activities-schema.xsd
1.05 - http://iatistandard.org/schema/downloads/iati-activities-schema.xsd
1.04 - http://iatistandard.org/104/schema/downloads/iati-activities-schema.xsd
1.03 - http://iatistandard.org/downloads/1.03/iati-activities-schema.xsd
1.02 - http://iatistandard.org/downloads/1.02/iati-activities-schema.xsd
1.01 - http://iatistandard.org/downloads/1.01/iati-activities-schema.xsd

**Comment by el-clemente** [comment]
Hello @Bjwebb, @stevieflow & @caprenter - the original issue that I reported seems to have been fixed as all of the urls taht are listed below send you to the expected XSD schema. Is this correct?

2.01 - http://iatistandard.org/downloads/2.01/iati-activities-schema.xsd
1.05 - http://iatistandard.org/downloads/1.05/iati-activities-schema.xsd 
1.04 - http://iatistandard.org/downloads/1.04/iati-activities-schema.xsd 
1.03 - http://iatistandard.org/downloads/1.03/iati-activities-schema.xsd
1.02 - http://iatistandard.org/downloads/1.02/iati-activities-schema.xsd
1.01 - http://iatistandard.org/downloads/1.01/iati-activities-schema.xsd

**Comment by Bjwebb** [comment]
Yes, I think that's correct, so I'm closing this issue.

Also, for the benefit of anyone referring to this issue in future http://iatistandard.org/downloads/iati-activities-schema.xsd redirects to the 1.05 schema, as explained here: http://www.aidtransparency.net/news/iati-standard-version-2-01-is-now-available-for-use

**Comment by stevieflow** [comment]
One thing I noticed is that a URL without the decimal in the version number, also works - eg:

http://iatistandard.org/105/schema/downloads/iati-activities-schema.xsd

These are the URLs that are pointed to from the site(s)
