### ISSUE TITLE
404 page is missing left navigation

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Websites#145]
e.g. http://iatistandard.org/a/b/c

Doesn't have any navigation on the left.

This is Sphinx's default for pages that aren't in the navigation, but it may be possible for us to override this.

**Comment by caprenter** [comment]
I'm not sure it is clear what the left navigation should contain in this instance. 

I think this is ok as it is. 

@Bjwebb I would suggest closing this issue

**Comment by Bjwebb** [comment]
The left hand navigation shown on IATIStandard is the same everywhere else, it just changes in terms of which bits are expanded. I would suggest that the 404 page should have a non-expanded version.

**Comment by caprenter** [comment]
A non-expanded version would simply mirror the links in the main header navigation, but it would give a user is a way to expand those sections to start to make their way somewhere else.

**Comment by Bjwebb** [comment]
Yep.
