### ISSUE TITLE
Change IATI REGISTRY/DATA label on top nav 

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Websites#146]
Change IATI REGISTRY/DATA to IATI DATA:

- [ ]  aidstranspareny.net
- [x] iatistandard.org
- [x] iatiregistry.net: https://github.com/okfn/ckanext-iati/issues/55
- [ ] support.iatistandard.org

**Comment by caprenter** [comment]
This change has also been made at iatistandard.org
@Bjwebb you were planning on changing the other 2 sites under your control yesterday/

**Comment by stevieflow** [comment]
I've also asked CKAN team to make a similar change on the live Registry

**Comment by Bjwebb** [comment]
The registry change is now live, and I have also made the change to the two other sites.
