### ISSUE TITLE
Invalid mailto urls

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Websites#151]
These exist because because Sphinx made the wrong assumption about an at sign (we can fix these by replacing @ with `\@`).

| urlname | parentname |
| --- | --- |
| mailto:/%40type | http://iatistandard.org/upgrades/decimal-upgrade-to-1-03/1-03-changes/ |
| mailto:contact-info/%40type | http://iatistandard.org/activity-standard/iati-activities/iati-activity/contact-info/ |
| mailto:iati-activities/%40linked-data-default | http://iatistandard.org/activity-standard/iati-activities/iati-activity/ |
| mailto:iati-activity/%40default-currency | http://iatistandard.org/activity-standard/summary-table/ |
| mailto:iati-organisation/%40default-currency | http://iatistandard.org/activity-standard/summary-table/ |
| mailto:location/coordinates/%40precision | http://iatistandard.org/activity-standard/iati-activities/iati-activity/location/exactness/ |
| mailto:location/location-id/%40code | http://iatistandard.org/upgrades/decimal-upgrade-to-1-04/location-summary/ |
| mailto:location/location-id/%40vocabulary | http://iatistandard.org/upgrades/decimal-upgrade-to-1-04/location-summary/ |
| mailto:n/%40vocabulary | http://iatistandard.org/upgrades/decimal-upgrade-to-1-03/1-03-changes/ |
| mailto:other-identifier/owner-org/%40ref | http://iatistandard.org/201/activity-standard/summary-table/ |
| mailto:reporting-org/%40ref | http://iatistandard.org/201/activity-standard/iati-activities/iati-activity/iati-identifier |

**Comment by Bjwebb** [comment]
Added two more rows to the end of the table.

**Comment by samuele-mattiuzzo** [comment]
Still valid, sadly
