### ISSUE TITLE
Invalid GitHub urls

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Websites#152]
These are mostly because the master branch no longer exists

| urlname                                                                                      | parentname                                       |
|----------------------------------------------------------------------------------------------|--------------------------------------------------|
| https://github.com/IATI/IATI-Codelists/blob/master/codelist.xsd                              | http://iatistandard.org/developer/ssot/proposal/ |
| https://github.com/IATI/IATI-Codelists/blob/master/mapping.xml                               | http://iatistandard.org/developer/ssot/proposal/ |
| https://github.com/IATI/IATI-Rulesets/blob/master/README.rst                                 | http://iatistandard.org/developer/ssot/proposal/ |
| https://github.com/IATI/IATI-Rulesets/blob/master/rulesets/standard.json                     | http://iatistandard.org/developer/ssot/proposal/ |
| https://github.com/IATI/IATI-Rulesets/blob/master/schema.json                                | http://iatistandard.org/rulesets/ruleset-spec/   |
| https://github.com/IATI/IATI-Rulesets/blob/master/testrules.php                              | http://iatistandard.org/developer/ssot/proposal/ |
| https://github.com/IATI/IATI-Rulesets/blob/master/testrules.py                               | http://iatistandard.org/developer/ssot/proposal/ |
| https://github.com/IATI/IATI-Standard-SSOT/blob/master/README.rst#building-the-documentation | http://iatistandard.org/developer/ssot/proposal/ |
| https://github.com/organizations/IATI/dashboard/issues/assigned                              | http://iatistandard.org/developer/ssot/proposal/ |

**Comment by caprenter** [comment]
Commit above fixes all the links above apart from:
https://github.com/IATI/IATI-Rulesets/blob/master/schema.json	
referenced from
http://iatistandard.org/rulesets/ruleset-spec/

**Comment by caprenter** [comment]
@bjwebb I can't see where the source is for the final fix. can you point me to it pls?

**Comment by Bjwebb** [comment]
@caprenter https://github.com/IATI/IATI-Rulesets/blob/version-2.01/SPEC.rst

**Comment by caprenter** [comment]
Final link fixed in https://github.com/IATI/IATI-Rulesets/commit/dc33733bae8a24071aae24a830b8582ed370872d
