### ISSUE TITLE
Links to old codelist API 404

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Websites#155]
This may, or may not be a bug.

| urlname | parentname |
| --- | --- |
| http://data.aidinfolabs.org/data/ | http://iatistandard.org/codelists/codelist-api/ |
| http://data.aidinfolabs.org/data/codelist.xml | http://iatistandard.org/codelists/codelist-api/ |

**Comment by caprenter** [comment]
The services at aidinfolabs are no longer provided under IATI funding. It sort of says this on the page. 

This could be dealt with along with the Update codelist API page issue:
https://github.com/IATI/IATI-Extra-Documentation/issues/266
