### ISSUE TITLE
All versions pages need update for Jan 6th

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Websites#156]
The All versions page needs an update here:
http://wip.iatistandard.org/201/upgrades/all-versions/
http://wip.iatistandard.org/105/upgrades/all-versions/

and possibly here:
http://wip.iatistandard.org/104/upgrades/all-versions/

**Comment by Bjwebb** [comment]
Done https://github.com/IATI/IATI-Guidance/commit/c0541df25fb500f84e7d0483ae9a817da40ec370
