### ISSUE TITLE
Broken links on index pages

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Websites#163]
```
201/how-to-publish/prepare-your-org/	http://iatistandard.org
201/how-to-publish/regular-updates/	http://iatistandard.org
201/how-to-publish/select-publishing-tool/	http://iatistandard.org
how-to-publish/prepare-your-org/	http://iatistandard.org/105/
how-to-publish/regular-updates/	http://iatistandard.org/105/
how-to-publish/select-publishing-tool/	http://iatistandard.org/105/
```

**Comment by caprenter** [comment]
I think we also have problems with 104:
At: http://iatistandard.org/104/
Links under:
IATI data, IATI in detail, and Support
all point at iatistandard.org

**Comment by caprenter** [comment]
Ok - the 1.04 problems are fixed directly on the live server by editing the index.html directly

**Comment by Bjwebb** [comment]
http://dev.iatistandard.org/105/ is now fixed (I'll make that live along with other changes next week), and I've update http://iatistandard.org/ straight to live as it's just a static page.
