### ISSUE TITLE
Archived versions of standard - XML examples not displaying (on Org standard pages)

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Websites#170]
I noticed on the 1.03 site that the XML example is not rendering as a `code block`:

http://iatistandard.org/103/organisation-standard/budget-organisation/index.html

Specifically, this seems to be on just the Organisation standard side of things - as Activity standard pages seem OK:

http://iatistandard.org/103/activities-standard/iati-identifier/index.html (I havent checked all)

I recall that the Org standard was using code examples from _within_ the Wordpress CMS - whereas the activity standard was pulling from the wiki.  This might be the reason.  @Bjwebb @caprenter could have ideas

**Comment by samuele-mattiuzzo** [comment]
Archived version (which will also soon be deprecated), no further work on this
