### ISSUE TITLE
2.02 website missing

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Websites#179]
http://iatistandard.org/202/ is a blank page
http://iatistandard.org/ also has broken styles

**Comment by allthatilk** [comment]
Memory got full while script was running. In process of fixing now.

**Comment by hayfield** [comment]
http://iatistandard.org/202/ now works gain
http://iatistandard.org/ should start working again soon

**Comment by hayfield** [comment]
It's working again now

**Comment by Bjwebb** [comment]
Great, thanks!
