### ISSUE TITLE
Add an iatistandard.org redirect for latest version

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Websites#191]
E.g. this:
http://iatistandard.org/activity-standard/iati-activities/iati-activity/

…currently redirects to:
http://iatistandard.org/203/activity-standard/iati-activities/iati-activity/

It would be cool to be able to be explicit about this, e.g. with:
http://iatistandard.org/latest/activity-standard/iati-activities/iati-activity/

Context: I notice the IATI standard docs very often link to some specific version of the standard, when they probably actually mean to link to the latest version. It might be clearer how to do this by adding this explicit redirect.

**Comment by samuele-mattiuzzo** [comment]
Sensible!

**Comment by andylolz** [comment]
I think you’ve misunderstood. But I appreciate this is a minor issue, so it doesn’t matter.
