### ISSUE TITLE
IATI Support "request received" message does not say whether the request was received

### ISSUE THREAD

**Issue by markbrough** [IATI/IATI-Websites#225]
I submitted a request following the "Submit a request" link on http://discuss.iatistandard.org which sent me to this URL:
https://support.iatistandard.org/hc/en-us/requests/new

Once I clicked submit, the following page was displayed, which does not make clear what happened to the request. However, I know that the request was received, as I received an email in my inbox shortly thereafter.
![grafik](https://user-images.githubusercontent.com/688113/47664089-38d72000-db96-11e8-95ad-98a74c1712e2.png)

The URL of this page was:
https://support.iatistandard.org/hc/en-us?return_to=%2Fhc%2Frequests

**Comment by PetyaKangalova** [comment]
Hi @markbrough  Did you sign in when you submitted the request?  We use Zendesk for the IATI support helpdesk and will need to check with them what the functionality is if you are not signed in.

**Comment by markbrough** [comment]
No, I wasn't signed in. I wonder if it is partly due to the work of the tech team to "disable" support.iatistandard.org when we moved over to using discuss.iatistandard.org instead as a discussion forum? Perhaps there is something wrong in IATI's custom theming of Zendesk?

**Comment by amy-silcock** [comment]
Hi @markbrough, I've changed the link on IATI Discuss to the contact page on the new IATI website. You're correct that the old page is linked to zendesk / the Discuss archive. However, updating the archive pages is  not a priority area for us to work on.

**Comment by samuele-mattiuzzo** [comment]
Thanks @markbrough then we close this issue and raise a new one for the Support link (which btw, if you click, redirects back to iatistandard.org, albeit to a wrong url)
