### ISSUE TITLE
"Tools and resources for data use" has no href

### ISSUE THREAD

**Issue by jpmckinney** [IATI/IATI-Websites#240]
On https://iatistandard.org/en/guidance/publishing-data/data-quality/ways-of-visualising-iati-data/

`href` should be https://iatistandard.org/en/using-data/iati-tools-and-resources/

**Comment by andylolz** [comment]
@jpmckinney I think the repo you’re after is https://github.com/IATI/IATI-Standard-Website

**Comment by jpmckinney** [comment]
That repo seems to be about the code that powers the CRM, whereas this repo is described as "Used to track issues about the content of IATI websites". I opened an issue there anyhow.

**Comment by samuele-mattiuzzo** [comment]
Thanks @jpmckinney ! Yes, @andylolz is correct, the `IATI-Standard-Website` is the one you're after rather than this! I'll close this issue here and will triage and carry on with yours in the other repo!
