### ISSUE TITLE
Using IATI data

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Websites#59]
Need a clear page that signposts people to the relevant resources

Currently, there is:

http://iatiregistry.org/using-iati-data
http://iatistandard.org/getting-started/tools-to-help/ (maybe not all pages)

and

http://www.aidinfolabs.org/393

**Comment by amy-silcock** [comment]
Using IATI Data guidance is now here: https://iatistandard.org/en/using-data/
