### ISSUE TITLE
HTML <tt> Tag. Not Supported in HTML5.

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Websites#90]
We should move away from the use of the tt tag:
See;
http://www.w3schools.com/tags/tag_tt.asp

An example of usage at time of writing:
http://iatistandard.org/rulesets

**Comment by caprenter** [comment]
I think this may have been fixed now @Bjwebb . Can we close it?

**Comment by Bjwebb** [comment]
Yes, this can be closed. This was an issue due to an issue in Sphinx - https://bitbucket.org/birkenfeld/sphinx/issue/1476/tag-is-obsolete - which is fixed in the latest version.
